### PR TITLE
Bump to 2.74.0

### PR DESCRIPTION
**Pull request by tschoonj**

### CODE REVIEW

**Comment by hmaarrfk** [comment]
how did you generate these gir files?

**Comment by tschoonj** [comment]
Manually, for some reason those generated by CI were broken, but when I generated them myself on a Windows VM, they were fine.

I don't know if this will still be a concern for version 3.

**Comment by hmaarrfk** [comment]
it is, i'm having trouble generating them. if you could help that is the last step.

**Comment by hmaarrfk** [comment]
they too only include macros, but no functions..

**Comment by tschoonj** [comment]
Nah can't help you with that, don't have my Windows dev VM anymore.

**Comment by hmaarrfk** [comment]
if you remember the commands i can run them. i just don't really understand g-ir ...

**Comment by hmaarrfk** [comment]
did you just run it "normally" then copy the files over from the build?

**Comment by tschoonj** [comment]
I remember just doing the conda build on that VM, and it would have the correct files, so extracted them and put them in the repo.

**Comment by hmaarrfk** [comment]
interesting....

**Pull request merged**
